[package]
name = "glassbox"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
dft = "0.5.5"
discord-rich-presence = "1.0.0"
eframe = "0.33.0"
egui = "0.33.0"
egui_extras = { version = "0.33.0", features = ["image"] }
env_logger = "0.11.8"
image = "0.25.8"
iris-lib = "0.1.0"
log = "0.4.28"
raw-window-handle = "0.6.2"
rfd = "0.15.4"
rodio = "0.21.1"
taglib = "1.0.0"

[dependencies.windows]
version = ">=0.59, <=0.62"
features = [
    "Data_Xml_Dom",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
]

[patch.crates-io]
taglib = { git = "https://github.com/yourname3/taglib-rust.git" }
